### ISSUE TITLE
Include QR code for join.status.im/chat/...

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/universal-links-handler#25]
## Problem
Currently join.status.im/user/... shows a QR code for the chat key and ENS name (whichever is in the url). In case of a public or group chat, no QR code is shown.

Copy could use updates:

❌  Chat in a public channel #status in Status
✔️  Join public channel #status on Status

❌ Header `Status`
✔️ Header `#Status`

![Screenshot_20200212-135245_Firefox](https://user-images.githubusercontent.com/35233054/74336709-1d018880-4d9f-11ea-891d-6fa9e209afb0.jpg)

**Comment by hesterbruikman** [comment]
@jakubgs do you have any thoughts on how to add a QR code for public channels?
Also, if you can point me to the language file I can make the copy edits of this issue.

**Comment by jakubgs** [comment]
I can do this. It should be easy.

**Comment by jakubgs** [comment]
But there is an issue here. Because the app has no way of distinguishing between a username and a chat name. Lets say I have a QR code for `whatever`, is that a `whatever.stateofus.eth` ENS or is that a `#status` chat name?

There are 2 ways of solving this as far as I can tell:

1. Use the `status-im://` format in QR codes so it's contents are:
  - `status-im://chat/public/whatever` or
  - `status-im://user/whatever`
2. Always provide full ENS name, and always prefix chat names with `#`:
  - `whatever.stateofus.eth`
  - `#whatever`

The former is easier to handle, but the latter is more concise and gives smaller QR codes.

This needs to be decided upon and implemented both in the app and in this repo.
My https://github.com/status-im/status-react/issues/10017 issue touches on this specific subject.
