### ISSUE TITLE
Handle referral url

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/universal-links-handler#39]
## Problem
Join.status.im needs to detect whether the join url includes an invite code. If the url includes an invite code (https://join.status.im/status/invite-id or https://join.status.im/user/hester.stateofus.eth/invite-id), this code needs to be passed along to the app directly or through the Play Store.

### Current behavior
Url with invite-id redirects to status.im/get (currently url is https://join.status.im/i/invite-id, this is to be updated for the invite-id to be added to existing share urls

### Expected behavior
Existing share url with invite-id passes invite id along as referrer

## Background
As part of the referral program, the 'invite friends' url will include an invite code. Under conditions, the user who shares the invite url will receive a reward.

When a recipient of the invite uses the url to download and install status, and purchase a Starterpack on Android, the invite code is posted back to a contract, to release funds.

**Comment by hesterbruikman** [comment]
cc @jakubgs @Ferossgp

**Comment by jakubgs** [comment]
Questions:

* How exactly is this different form https://github.com/status-im/universal-links-handler/issues/31?
* What does `added to existing share urls` mean? Do you mean "deep links"l?
* Is there any specific technical reason why this has to be part of path and not an argument?
  - Example: `/status?invite=<ID>` instead of `/status/invite-id`, this is already in place.

**Comment by Ferossgp** [comment]
@jakubgs yes, this is the same as #31 :+1:

**Comment by jakubgs** [comment]
Then this has already been implemented in #33.
