### ISSUE TITLE
Contact code is too long

### ISSUE THREAD

**Issue by chadyj** [status-im/universal-links-handler#7]
The contact code is too long and can't be displayed at many regular resolutions. Eg https://get.status.im/user/0x044166fa04e967e333211ae0cc1087c9c74e95e71d210dfd9509da76cf1af37c8968479

Can the contact code be split across 3 lines or some other solution so the full code can be easily viewed?

![screen shot 2018-07-31 at 10 28 58 am](https://user-images.githubusercontent.com/116099/43450582-51ede3c8-94b3-11e8-93b2-e1423b1d793b.png)

cc @noman-land

**Comment by chadyj** [comment]
Was thinking how the app displays it wrapping to 2 or 3 lines

![image-1](https://user-images.githubusercontent.com/116099/43451101-77bb97fc-94b4-11e8-86d0-c80e30623ac1.jpg)

**Comment by chadyj** [comment]
Eg something similar to this:

```
<span style="width:100px; word-wrap:break-word; display:inline-block;"> 
   ACTGATCGAGCTGAAGCGCAGTGCGATGCTTCGATGATGCTGACGATGCTACGATGCGAGCATCTACGATCAGTC
</span>
```

**Comment by pilu** [comment]
we can also start thinking about compressing the public keys, so that we can have a string that is half the size + 2 characters.
We are using the normal uncompressed public keys used in ethereum (they starts with `0x04`), but we could easily compress it using `0x02` and `0x03`. the client then needs to understand that is a compressed one and uncompress it when needed

**Comment by chadyj** [comment]
And ideally, soon we can support ens eg https://get.status.im/user/chadyj.stateofus.eth too which cuts things down and gives a greater sents of identity.

**Comment by chadyj** [comment]
@pilu Shorter keys seem more nimble and usable. Is there any downside to compressing the keys?
